### ISSUE TITLE
The matchPlayer function is called incorrectly

### ISSUE THREAD

**Issue by Wafiismail27** [cstefFlexin/gamemaker#1]
**Expected Behaviour**
 The match making function should be called with the number of allowed participants looping through the whole list
 
 **Behaviour seen**
 The match making function is looped between the first same participants again and again. 
 
 Maybe a quick fix, i haven't checked out the lib's source

**Comment by cestef** [comment]
It's been ages since I last touched this lol, I'll trust you on this one
